name: recipe
description: "Recipe app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
    
  flutter_bloc: ^8.1.3
  http: ^1.1.0
  equatable: ^2.0.5
  cached_network_image: ^3.2.3
  flutter_spinkit: ^5.2.0
  firebase_core: ^2.24.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  

  bloc_test: ^9.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/logo/banner.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/appIcon.png"
  min_sdk_android: 12
  adaptive_icon_foreground: "assets/logo/appIcon.png"
  adaptive_icon_background: "#FFA500"

flutter_native_splash:
  image: "assets/logo/splash.png"
  color: "#FFA500"
  android: true
  ios: true
  web: true

  # Resize options
  android_gravity: center # Ensures icon is centered
  ios_content_mode: scaleAspectFill

  android_12:
    image: "assets/logo/splash.png"
    color: "#FFA500"


