// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKBZ2ZcEAT4M-gL-HZgHgYTnXo43XnVlM',
    appId: '1:1048278967155:web:3726e7f82f04f321919b06',
    messagingSenderId: '1048278967155',
    projectId: 'butterfly-studios',
    authDomain: 'butterfly-studios.firebaseapp.com',
    storageBucket: 'butterfly-studios.firebasestorage.app',
    measurementId: 'G-42HYS6QQ20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcDNMy1kr0pmqh3ori8pjGwldriej8DlA',
    appId: '1:1048278967155:android:fdd3dbd6156b59c8919b06',
    messagingSenderId: '1048278967155',
    projectId: 'butterfly-studios',
    storageBucket: 'butterfly-studios.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAggmluskvXcRT-VXLJ2J9IreX-jWf9O_M',
    appId: '1:1048278967155:ios:3fad65a2b6baca52919b06',
    messagingSenderId: '1048278967155',
    projectId: 'butterfly-studios',
    storageBucket: 'butterfly-studios.firebasestorage.app',
    iosBundleId: 'com.example.recipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAggmluskvXcRT-VXLJ2J9IreX-jWf9O_M',
    appId: '1:1048278967155:ios:3fad65a2b6baca52919b06',
    messagingSenderId: '1048278967155',
    projectId: 'butterfly-studios',
    storageBucket: 'butterfly-studios.firebasestorage.app',
    iosBundleId: 'com.example.recipe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKBZ2ZcEAT4M-gL-HZgHgYTnXo43XnVlM',
    appId: '1:1048278967155:web:f5da444e2dfd13cf919b06',
    messagingSenderId: '1048278967155',
    projectId: 'butterfly-studios',
    authDomain: 'butterfly-studios.firebaseapp.com',
    storageBucket: 'butterfly-studios.firebasestorage.app',
    measurementId: 'G-6F1E6X5XWG',
  );
}
